export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

export const TIMING_LIST_REQUEST = 'TIMING_LIST_REQUEST';
export const TIMING_LIST_SUCCESS = 'TIMING_LIST_SUCCESS';
export const TIMING_LIST_FAIL = 'TIMING_LIST_FAIL';

export const HOTDEALS_LIST_REQUEST = 'HOTDEALS_LIST_REQUEST';
export const HOTDEALS_LIST_SUCCESS = 'HOTDEALS_LIST_SUCCESS';
export const HOTDEALS_LIST_FAIL = 'HOTDEALS_LIST_FAIL';
